---
newrelic:
  - account: 4339676
    tags:
      environment: preprod
      workspace: default

services:
  - name: Ecommerce Web
    description: null
    permissions: PUBLIC_READ_WRITE
    components:
      - AWS ECS
      - HTTP Flows
  - name: Ecommerce Platform
    description: null
    permissions: PUBLIC_READ_WRITE
    components:
      - aws lambda
      - HTTP Flows span   

